
image: schickling/mysql-backup-s3

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - master
  variables:
    GIT_REMOTE_URL: https://github.com/ThomasBRN/tbarreno.git
    # specify `--force` as a flag for git pushes
    GIT_PUSH_FLAGS: '--force'
  script: dokku-deploy
  after_script: [dokku-unlock]
