name: Run CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.event.repository.name }}:latest, ${{ github.repository }}:latest

